### ISSUE TITLE
Trade Overview page: calculations incorrect

### ISSUE THREAD

**Issue by rcoenen** [askmike/gekko#1773]
**Note: for support questions, please join our [Discord server](https://discord.gg/26wMygt)**

* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Action taken** (what you did)
Had the bot execute a live trade

* **Expected result** (what you hoped would happen)
Correct calculation of
- profit (seems incorrect to mee, see orange arrows in screenshot below) I am unsure but it looks like the market went up yet it shows a negative number...?

- roundtrip of 48 years?! (see pink arrows in screenshot below)

* **Actual result** (unexpected outcome)
Correct calculations

![error](https://user-images.githubusercontent.com/753704/35287461-4a2cf342-005a-11e8-97b7-b2753136c102.png)

**Comment by billymcintosh** [comment]
There's an issue with Binance as well which I'm checking to see if it has been fixed yet before making a commit.    It may fix gdax also.

**Comment by rcoenen** [comment]
@billymcintosh interesting... is anyone even testing this other than me? I mean GDAX being (one of-) the largest exchange in the world.. I am surprised I am apparently the first one to run into this.

Also: Do you expect the bot to continue trading now? I have not seen any follow up trades - despite that BTC went up a lot today. I'd have expected a buy... can it be that the bot believes it traded in the past due to that bug and got stuck? ( I will keep it running for another day to see what happens - I don't want to restart it)

**Comment by rcoenen** [comment]
Guys I did some further testing: I tried to create a backtest with the exact same data and setting as my live bot. I took a screenshot of both live and backtest. Interestingly they show wildly different results.

1. As mentioned above the live bot is simply broken / incorrect as it reports an roundtrip exposure of 48 years.
2. The live bot shows only 1 green dot and it is **not on the graph line for some reason.** It sits below. (The red dot is missing b/c it's probably plotted 48 years before the start - so lets ignore.)
3. Live result: 6.11% vs 6.45224% in backtest. Weird, I am using the exact same data, strategy, time frame, parameters, etc.
4. Unlike the Backtest, the live bot does not show what the exact value of the BTC in EUR on GDAX was at time of start. However the graphline starts at almost exactly EUR 8800. The backtest claims the value was 9009 EUR. That's significantly different of course.
5. The first trade on live is at 2018-01-23 13:14 but the backtest is at 2018-01-23 12:13 - quite a difference


 



![compare](https://user-images.githubusercontent.com/753704/35304850-f822abd4-008e-11e8-9296-7ce84eed6f57.png)

**Comment by rcoenen** [comment]
OK another day, another update and good news:

The bot kept working and made a second (profitable!) trade despite the 1st trade seemingly having ended in the 1970s (according to the roundtrip table in screenshot in post above) 

The bad news: the roundtrip table is now missing. Also the graph shows only 2 data points, instead of 4 (it has execute 2 trades, so 4 data points: 2x buy and 2x sell) but it shows it incorrectly as 1 long trade. 

See below this is the same bot as above only a day later
![screencapture-ec2-35-177-184-17-eu-west-2-compute-amazonaws-1516802135498](https://user-images.githubusercontent.com/753704/35335769-5c1dda1c-010e-11e8-8d5f-5c6fae3da0e8.png)

**Comment by billymcintosh** [comment]
Back testing will buy and sell with no competition or latency, live trading doesn't have it so easy.     

If you're wanting more information than the UI shows, I recommend grepping the logs directory for your tradebot.  It will give you exact times and prices of trades.

**Comment by rcoenen** [comment]
@billymcintosh ok I was guessing that the backtesting would perform different because of latency, but still, the backtest graph shows a buy dot at around 12:00 whereas the live bot graph shows a dot at just after 13:00 - that is 1 hour difference. Bit much for network latency.
The time stamps on the live roundtrip claim everything is in UTC so I am assuming the time stamps on the backtest bot are also UTC

**Comment by billymcintosh** [comment]
1 hour is quite a gap but I've seen it happen.   Just this evening Gekko tried its first purchase at: 24-01-18 20:26:03 and ultimately got a semi-filled order complete at 24-01-18 20:51:27. 

Everything should be in UTC.

**Comment by rcoenen** [comment]
Roundtrips are plain wrong in live trading Web UI

![screengrab](https://user-images.githubusercontent.com/753704/35995438-3f695a6e-0d0b-11e8-8272-3b1d935b7b45.png)

**Comment by askmike** [comment]
This bug has been fixed in the latest develop version, you can use that! I will release a new stable version soon so no one should encounter this anymore.

**Comment by rcoenen** [comment]
@askmike I am running the development branch. Which version did fix this? In any case I will get the latest dev branch and restart the bot.

**Comment by rcoenen** [comment]
@askmike ok testing now with d953a37f7ebe04262b7c2d311fa2dbcf536097e3 -- live bot trading EUR - BTC on GDAX / Stoch RSI

**Comment by rcoenen** [comment]
@askmike which bug was fixed? roundtrips not showing OR the green/red dots not being shown correctly on the graph? 
I am testing with d953a37 and the bot has executed 1 trade (sell) since yesterday, so no roundtrip data yet, but the red dot does not show exactly aligned on the graph.

<img width="1280" alt="dot" src="https://user-images.githubusercontent.com/753704/36064009-8d19b322-0e7c-11e8-9d10-caaba1639351.png">

**Comment by rcoenen** [comment]
@askmike  this ticket should not have been closed - it is still not fixed in d953a37

![image](https://user-images.githubusercontent.com/753704/36077125-9582c642-0f5e-11e8-8237-95a0e9d1082c.png)

**Comment by chris-sta** [comment]
I am experiencing the same issue with the newest gekko-develop. Can someone please help ?

**Comment by chris-sta** [comment]
And it is also exactly 48 years.

**Comment by chris-sta** [comment]
![untitled](https://user-images.githubusercontent.com/36948240/36937419-f7e3de50-1f0a-11e8-8ae7-eb268c86152d.jpg)

Same issue persists. Any help ?

**Comment by rcoenen** [comment]
I am not getting the impression that the devs actually trade with real bitcoins themselves or they'd have noticed this ages ago

**Comment by askmike** [comment]
This issue slipped my attention, will have a look. And yes I am trading
using gekko with real bitcoin.

**Comment by askmike** [comment]
Can you reopen this ticket?

**Comment by rcoenen** [comment]
@askmike hey Mike, thanks for picking this up again. I cannot re-open the ticket as per the GitHub rules I can only re-open if I closed the ticket myself. Since you closed this one I suppose you're the one that has the ability to re-open this ticket?

**Comment by askmike** [comment]
oops!
