### ISSUE TITLE
Mailing

### ISSUE THREAD

**Issue by AddicTed2Github** [askmike/gekko#398]
Hello, 

I've just started using gekko and everything works fine. I have enabled the mailing advisor and i'm receiving a mail even when there is no trend. Gekko's advice is to go "soft". 
Is it possible to only receive mail from Gekko when the advice is "short" or "long" ?

**Comment by 0b01** [comment]
I have addressed this problem in #402

**Comment by AddicTed2Github** [comment]
Thanks, i've seen that you made also a change in the mailer.js.
In order to use the muteSoft option, do i have to modify this document too ?
It is confusing me because you didn't add the muteSoft option in the config.mailer.

**Comment by 0b01** [comment]
I committed a bunch of changes altogether.

Here is the config file:

https://github.com/askmike/gekko/pull/402/commits/c31d73bcd07555b2d229914ef2ca6442e5d37038#diff-e56e394ecea23ca1d57f57a76ab38086R191

Regards,
Ricky

**Comment by AddicTed2Github** [comment]
I've made the changes in my [config.txt](https://github.com/askmike/gekko/files/405143/config_ETH.txt), the [adviceLogger.txt](https://github.com/askmike/gekko/files/405146/adviceLogger.txt) and the [mailer.txt](https://github.com/askmike/gekko/files/405145/mailer.txt).

With a candleSize of 60 in the config.js, i'm still receiving mail every hour : 

> Gekko is watching Poloniex and has detected a new trend, advice is to go soft.
> The current ETH price is 0.01848102

![gekko_mail_screenshot](https://cloud.githubusercontent.com/assets/20857750/17458672/ad178aee-5bb5-11e6-92f7-374134411b7f.png)

Here is the real-time output.log of these mail: [gekko_realMode-BTC-ETH.txt](https://github.com/askmike/gekko/files/405149/gekko_realMode-BTC-ETH.txt).

**Comment by 0b01** [comment]
I'm not sure why it's not working. Did you run the program after changing the config? or did you change the config while it's running?

**Comment by AddicTed2Github** [comment]
I did this : 
1. Stop running gekko with `CTRL+C`
2. Change the files
3. Run gekko again.

**Comment by 0b01** [comment]
Not sure why. It's working for me. :8ball:

**Comment by AddicTed2Github** [comment]
My bad, i did a reboot and it's good now. I might had an instance of gekko running background. 
Sorry for the bother and thanks for the help.

**Comment by askmike** [comment]
sorry for the late response, I am currently traveling and my laptop broke down. Will look at it as soon as possible!
